export default {
     LOGIN_REQ : "LOGIN_REQ",
     LOGIN_RESPONSE : "LOGIN_RESPONSE",

     LOGOUT_REQ : "LOGOUT_REQ",
     LOGOUT_RESPONSE : "LOGOUT_RESPONSE",    
     LOGOUT_USER : "LOGOUT_USER",
    
     CUR_USER_REQ : "CUR_USER_REQ",
     CUR_USER_RESP : "CUR_USER_RESP",

     UNAUTHORIZED_ERROR : "UNAUTHORIZED_ERROR",
     CLEAR_ERROR_RES : "CLEAR_ERROR_RES",
};